[build]
builder = "nixpacks"

[deploy]
startCommand = "cd src && python -m guardian.guardian"
healthcheckPath = ""
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
